import torch
from kokoro import KPipeline

pipeline = KPipeline(lang_code='a')

text = """
The performance of traditional machine learning algorithms heavily depends on the assumption that the training and test data are independent and identically distributed (IID). However, in wild environments, the test distribution often differs significantly from the training distribution. This mismatch can lead to spurious correlations, ultimately causing the machine learning models to perform poorly and become unstable. Unfortunately, this limitation severely hinders the use of machine learning in high-risk domains like autonomous driving [27, 38], medical treatment [36], and law [4].

In recent years, there has been a growing interest among researchers in addressing the Out-of-Distribution (OOD) generalization problem, where the IID assumption does not stand [66, 83]. This issue is addressed by various branches of research, such as invariant learning [1, 34, 13, 49, 50], distributionally robust optimization [67, 17, 75, 51, 52], stable learning [35, 65, 78, 82, 23, 14], and domain generalization [95, 76, 94, 42, 87]. Of these, domain generalization assumes the heterogeneity of training data. Specifically, domain generalization attempts to learn common or causal knowledge from multiple training domains to develop a model capable of generalizing to unseen test data.

Despite a quantity of interesting and instructive works in domain generalization, previously they do not have a common standard training and evaluation protocol. Aware of this problem, DomainBed [19] proposes a framework for the hyperparameter search and model selection of domain generalization. It also sets a standard for experimental details like the model backbone, data split, data augmentation, etc. This unifies the protocol of domain generalization for subsequent works to follow. Nevertheless, conflicts remain between the current standard protocol and the accurate and reliable evaluation of OOD generalization ability. Since domain generalization is depicted as the ability to learn a model from diverse training domains that can generalize to unseen/unknown test data [76, 95], we should try to mitigate possible test data information leakage for a more precise evaluation of the OOD generalization ability.

In the current protocol, two key factors show the potential risk of test data information leakage. We make two recommendations for fairer and more accurate evaluation.

Recommendation 1Domain generalization algorithms should adopt self-supervised pretrained weights or random weights as initialization when evaluated and compared with each other.
Most domain generalization algorithms take advantage of ImageNet supervised pretrained weights [15, 19] for better performance and faster convergence. Yet this introduces the information on both images and category labels in ImageNet, which may bear a resemblance to the test domain. Through comprehensive experiments, we demonstrate that more utilization of supervised pretrained weights and less utilization of training data can contribute to higher test domain performance under many common settings of domain generalization. This reveals that the ImageNet supervised pretrained weights may play a leading role in the test domain performance. Thus the accurate evaluation of OOD generalization is violated since the test domain performance does not really come from the generalization from training domains to test domains, for which most domain generalization algorithms are designed, but from the utilization of the supervised pretrained weights. We also demonstrate that when a test domain is quite similar to the ImageNet dataset, such a phenomenon becomes most evident while it does not occur if the test domain is rather different from ImageNet. This further confirms the test data information leakage.

To address such an issue, it is safest to train from scratch to purely evaluate domain generalization. However, on one hand, with the remarkable development and broad application of pretrained models these days [5, 60], it is too limited and not common practice to train from scratch in real applications without benefiting from pretraining. On the other hand, most of commonly used domain generalization datasets like PACS [39] and VLCS [30] are not large enough to support training from scratch. Thus we investigate different pretrained methods and model backbones towards a set of pretrained weights with which there is less test data information leakage and we can still conduct a relatively accurate evaluation of OOD generalization. Based on our experimental findings, we suggest that self-supervised pretrained weights are a good alternative.

Recommendation 2Domain generalization algorithms should be evaluated on multiple test domains.
For each trained model, domain generalization algorithms are typically evaluated on a single test domain. Before DomainBed, the choice of hyperparameters is not well specified, and there is a chance that model selection is conducted with the help of test data, i.e., the oracle model selection [19]. This can introduce information leakage from the test data and undermine the validity of the evaluation. Even following the standard protocol of DomainBed, such a possibility still exists since the search space of hyperparameters could be pre-selected with the information of oracle data and fixed apriori for the DomainBed model selection pipeline. Moreover, the ultimate goal of domain generalization is to develop models that can generalize well to a wide range of unseen domains in real-world applications instead of tuning a set of hyperparameters for one single test domain. The current protocol allows models to select different hyperparameters for each test domain, which may not reflect the real-world scenario and could be inconsistent with the original purpose of domain generalization [90]. We suggest that we should evaluate algorithms on multiple test domains for each trained model since we empirically demonstrate that by doing so, the potential leakage from oracle model selection can be greatly mitigated.

New leaderboards
Based on the aforementioned recommendations, we have conducted a re-evaluation of ten representative domain generalization algorithms following the revised protocol and presented three sets of new leaderboards. For ResNet50 [21] that is employed in the current protocol, we provide leaderboards with MoCo-v2 [10] pretraining across all commonly used datasets, and leaderboards with no pretraining on large-scale datasets like DomainNet [59] and NICO++ [90]. In addition, to support comparisons on more advanced network architectures like vision transformers, we also provide leaderboards for ViT-B/16 [16] with MoCo-v3 [12] pretraining. Combined with our previous analyses, the change in rankings of algorithms between the new leaderboard and the old one also implies that we are taking risks to improperly evaluate and rank existing methods with the current evaluation protocol. We believe the revised protocol and the leaderboards will stimulate future research in the field of domain generalization with more precise evaluation.
"""

audio_list = []
generator = pipeline(text, voice='af_heart')
for i, (gs, ps, audio) in enumerate(generator):
    audio_list.append(audio)

main_audio = torch.zeros(0)

for audio in audio_list:
    main_audio = torch.cat((main_audio, audio), dim=0)